/**
 * @file equipment.h
 *
 * @brief Equipment control framework interface.
 *
 * @details
 * This header defines the data types, callback interfaces, and public
 * APIs used to manage semiconductor equipment.
 *
 * The Equipment module provides:
 *   - Equipment state management
 *   - Equipment command handling
 *   - Start, stop, and alarm callbacks
 *   - Generic equipment event notification
 *   - Thread synchronization using a POSIX mutex
 *
 * The module is designed to be used by higher-level components such as
 * TCP servers, worker threads, and other equipment-control modules.
 *
 * @note
 * This module uses POSIX pthreads and is intended for Linux/WSL.
 *
 * @author Your Name
 * @date 2026-09-18
 */
#ifndef EQUIPMENT_H
#define EQUIPMENT_H

#include <pthread.h>

/*===========================================================================
 * Equipment State
 *===========================================================================*/

/**
 * @brief Represents the current operational state of the equipment.
 */
typedef enum
{
    EQUIPMENT_IDLE,       /**< Equipment is idle. */
    EQUIPMENT_READY,      /**< Equipment is initialized and ready. */
    EQUIPMENT_RUNNING     /**< Equipment is currently running. */
} EquipmentState;

/*===========================================================================
 * Equipment Commands
 *===========================================================================*/

/**
 * @brief Commands that can be applied to the equipment state machine.
 */
typedef enum
{
    EQUIPMENT_CMD_INIT,   /**< Initialize equipment: IDLE -> READY. */
    EQUIPMENT_CMD_START,  /**< Start equipment: READY -> RUNNING. */
    EQUIPMENT_CMD_STOP    /**< Stop equipment: RUNNING -> READY. */

} EquipmentCommand;


/*===========================================================================
 * Equipment Events
 *===========================================================================*/

/**
 * @brief Events generated by the equipment.
 *
 * Events describe something that has happened in the equipment system,
 * whereas EquipmentCommand represents an action requested by a controller.
 */
typedef enum
{
    EQUIPMENT_EVENT_STARTED,  /**< Equipment successfully started. */
    EQUIPMENT_EVENT_STOPPED,  /**< Equipment successfully stopped. */
    EQUIPMENT_EVENT_ALARM     /**< Equipment alarm was raised. */

} EquipmentEvent;


/*===========================================================================
 * Forward Declaration
 *===========================================================================*/

/**
 * @brief Forward declaration of the Equipment structure.
 *
 * The complete structure definition is provided below. The forward
 * declaration allows callback function types to refer to Equipment
 * before the structure is fully defined.
 */
typedef struct Equipment Equipment;


/*===========================================================================
 * Callback Function Types
 *===========================================================================*/

/**
 * @brief Generic callback for equipment events.
 *
 * This callback provides a common event notification mechanism.
 * The event type identifies what happened, while the message provides
 * additional information about the event.
 *
 * @param equipment Pointer to the equipment instance.
 * @param event     Event generated by the equipment.
 * @param message   Additional information about the event.
 *
 * @return None.
 */
typedef void (*EquipmentEventCallback)(Equipment *, EquipmentEvent, const char *);


/*===========================================================================
 * Equipment Structure
 *===========================================================================*/

/**
 * @brief Represents a semiconductor equipment instance.
 *
 * The Equipment structure contains the equipment identity, current state,
 * registered callback functions, synchronization object, and runtime data.
 *
 * Each Equipment object maintains its own callback configuration.
 */
struct Equipment
{
    int id;
    /**< Unique identifier of the equipment. */

    char name[32];
    /**< Equipment name, for example "ETCH01". */

    EquipmentState state;
    /**< Current operational state of the equipment. */


    /* Callback functions */

    EquipmentEventCallback event_callback;
    /**< Generic callback invoked when an equipment event occurs. */


    /* Thread synchronization */

    pthread_mutex_t mutex;
    /**< Mutex used to protect shared equipment state. */


    /* Runtime data */

    int counter;
    /**< Runtime counter associated with the equipment. */
};


/*===========================================================================
 * Worker Thread Data
 *===========================================================================*/

/**
 * @brief Context information passed to a worker thread.
 *
 * This structure is used by the TCP server to provide a worker thread
 * with access to the connected client socket and the equipment instance.
 */
typedef struct
{
    Equipment *equipment;
    /**< Pointer to the equipment handled by the worker thread. */

    int thread_id;
    /**< Logical identifier assigned to the worker thread. */

} WorkerData;



/*===========================================================================
 * Equipment Management APIs
 *===========================================================================*/

/**
 * @brief Creates and initializes an Equipment object.
 *
 * Initializes the equipment identity, name, state, callback pointers,
 * mutex, and runtime data.
 *
 * @param equipment Pointer to the Equipment object to initialize.
 * @param id        Unique equipment identifier.
 * @param name      Name of the equipment.
 *
 * @return None.
 */
void equipment_create( Equipment *equipment, int id, const char *name);


/**
 * @brief Initializes the equipment.
 *
 * Attempts to transition the equipment from IDLE to READY.
 *
 * @param equipment Pointer to the equipment instance.
 *
 * @return None.
 */
void equipment_init(Equipment *equipment);


/**
 * @brief Starts the equipment.
 *
 * Attempts to transition the equipment from READY to RUNNING.
 * If successful, the registered start callback is invoked.
 *
 * @param equipment Pointer to the equipment instance.
 *
 * @return None.
 */
void equipment_start(Equipment *equipment);


/**
 * @brief Stops the equipment.
 *
 * Attempts to transition the equipment from RUNNING to READY.
 * If successful, the registered stop callback is invoked.
 *
 * @param equipment Pointer to the equipment instance.
 *
 * @return None.
 */
void equipment_stop(Equipment *equipment);


/**
 * @brief Prints the current equipment state.
 *
 * @param equipment Pointer to the equipment instance.
 *
 * @return None.
 */
void equipment_print_state(const Equipment *equipment);


/**
 * @brief Destroys an Equipment object.
 *
 * Releases resources associated with the equipment, including its mutex.
 *
 * @param equipment Pointer to the equipment instance.
 *
 * @return None.
 */
void equipment_destroy(Equipment *equipment);


/*===========================================================================
 * Callback Registration APIs
 *===========================================================================*/

 /**
 * @brief Registers a generic event callback for an equipment instance.
 *
 * The registered callback can receive different event types such as
 * STARTED, STOPPED, and ALARM.
 *
 * @param equipment Pointer to the equipment instance.
 * @param callback  Generic event callback function.
 *
 * @return None.
 */
void equipment_set_event_callback( Equipment *equipment, EquipmentEventCallback callback);


/**
 * @brief Raises an equipment alarm.
 *
 * Prints an alarm notification and invokes the registered alarm callback
 * when one is available.
 *
 * @param equipment Pointer to the equipment instance.
 * @param message   Description of the alarm condition.
 *
 * @return None.
 */
void equipment_raise_alarm( Equipment *equipment, const char *message);


/**
 * @brief Notify the registered callback about an equipment event.
 *
 * @param equipment Pointer to the equipment instance.
 * @param event     Equipment event type.
 * @param message   Optional message associated with the event.
 */
void equipment_notify_event(Equipment *equipment, EquipmentEvent event, const char *message);

#endif